import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://aegisco.vercel.app";

  const routes = [
    "",
    "/capabilities",
    "/capabilities/detection",
    "/capabilities/tracking",
    "/capabilities/classification",
    "/capabilities/neutralization",
    "/capabilities/command-control",
    "/capabilities/integration",
    "/products",
    "/products/aegis-core",
    "/products/aegis-tactical",
    "/products/aegis-mobile",
    "/products/aegis-shield",
    "/products/aegis-skywatch",
    "/products/aegis-command",
    "/products/aegis-sentinel",
    "/products/aegis-integrator",
    "/solutions",
    "/solutions/military",
    "/solutions/military/forward-operating-bases",
    "/solutions/military/naval",
    "/solutions/military/convoys",
    "/solutions/military/special-operations",
    "/solutions/military/air-defense",
    "/solutions/airports",
    "/solutions/critical-infrastructure",
    "/solutions/border-security",
    "/solutions/vip-protection",
    "/solutions/prisons",
    "/solutions/urban-security",
    "/solutions/maritime",
    "/company",
    "/about",
    "/about/leadership",
    "/about/history",
    "/about/partners",
    "/about/certifications",
    "/technology",
    "/news",
    "/news/press-releases",
    "/news/events",
    "/careers",
    "/careers/openings",
    "/careers/culture",
    "/investors",
    "/investors/financial-reports",
    "/investors/governance",
    "/contact",
    "/request-demo",
    "/demos",
    "/legal/privacy",
    "/legal/terms",
    "/legal/itar",
    "/legal/compliance",
    "/legal/export-control",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly" as const,
    priority: route === "" ? 1 : route.split("/").length <= 2 ? 0.8 : 0.6,
  }));
}
